import { openClassmatesSettings } from './plugin-settings-navigation.mjs';
import { chromium, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
const url = process.env.DSH_ACCEPTANCE_URL;
if (!url) throw Error('DSH_ACCEPTANCE_URL is required');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
const checks = [];
const root = '.test-output/enhancement';
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(url);
  await page.getByRole('button', { name: '设置', exact: true }).waitFor();
  await page.getByText('团队界面验收：两个界面成员', { exact: true }).first().click();
  const trigger = page.locator('.cmt-trigger');
  await expect(trigger).toHaveCount(1);
  await trigger.click();
  const panel = page.locator('[data-team-panel]');
  await expect(panel).toBeVisible();
  await expect(panel).toContainText('fixture/design-model');
  await expect(panel).toContainText('fixture/review-model');
  await expect(panel.locator('.cmt-member').filter({ hasText: '界面制作同学' })).toHaveCount(2);
  await expect(panel).toContainText('native-helper');
  await expect(panel).toContainText('负责人');
  await expect(panel.locator('.cmt-task').first()).toContainText('界面制作同学');
  const clipped = await panel.locator('.cmt-memberNameText, .cmt-memberText small').evaluateAll(elements => elements
    .filter(element => element.scrollWidth > element.clientWidth + 1)
    .map(element => element.textContent));
  if (clipped.length) throw Error('Important member information clipped: ' + JSON.stringify(clipped));
  await page.screenshot({ path: `${root}/team-desktop.png` });
  checks.push('one native Team action; frozen role, instance, request model, native member, task ownership readable');
  await panel.locator('.cmt-member').filter({ hasText: 'mobile-designer' }).click();
  await expect(trigger).toContainText('界面制作同学');
  await expect(trigger).toContainText('design-model');
  await expect(panel).toHaveCount(0);
  checks.push('native child navigation; role and model visible without opening panel');
  await trigger.click();
  await panel.focus();
  await page.keyboard.press('Escape');
  await expect(panel).toHaveCount(0);
  await expect(trigger).toBeFocused();
  checks.push('Escape restores trigger focus');
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('.cmt-triggerLabel')).toBeVisible();
  await trigger.click();
  await expect(panel).toContainText('fixture/design-model');
  const bounds = await panel.boundingBox();
  if (!bounds || bounds.x < -1 || bounds.x + bounds.width > 391) throw Error('Mobile panel clipped');
  await page.screenshot({ path: `${root}/team-mobile.png` });
  checks.push('390px member header and panel remain readable');
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('button', { name: '通用设置', exact: true }).click();
  await page.getByRole('button', { name: '深色', exact: true }).click();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await trigger.click();
  await page.screenshot({ path: `${root}/team-dark.png` });
  checks.push('native dark theme');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('button', { name: '通用设置', exact: true }).click();
  await page.getByRole('button', { name: '浅色', exact: true }).click();
  await page.getByRole('button', { name: '关闭', exact: true }).click();
  await openClassmatesSettings(page);
  await expect(page.getByRole('button', { name: '打开角色配置助手', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '新建角色', exact: true })).toBeVisible();
  await page.screenshot({ path: `${root}/settings.png` });
  await page.getByRole('button', { name: '开始任务', exact: true }).click();
  await expect(page.getByText('选择一个工作区开始', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: '角色配置助手', exact: true })).toHaveCount(0);
  const composer = page.getByRole('textbox').last();
  await expect(composer).toBeEditable();
  await composer.fill('请简短回复以验证新的任务会话。');
  await composer.press('Enter');
  await expect(page.getByText('本地验收回复：运行时与界面已连通。此回复来自固定测试模型，不代表真实模型推理结果。', { exact: true })).toBeVisible();
  await page.screenshot({ path: `${root}/start-task.png` });
  checks.push('task opens in workspace, allows conversation, uses host model; retired configuration assistant absent');
  if (errors.length) throw Error('Page errors: ' + errors.join('; '));
  await writeFile(`${root}/browser-report.json`, JSON.stringify({ checkedAt: new Date().toISOString(), model: 'local deterministic fixture', checks, pageErrors: errors }, null, 2));
  console.log(JSON.stringify({ checks, pageErrors: errors }));
} finally { await browser.close(); }
